spring:
  profiles:
    active: dev
  data:
    cassandra:
      schemaAction: create_if_not_exists
      basePackages: com.yidoughi.repository
      keyspaceName: mykeyspace
      contactPoints: localhost
      port: 9042

application:
  name: spring, kafka and cassandra example!
  version: 0.0.1

server:
  port: 8888
  servlet:
    session:
      cookie:
        http-only: true


